# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude: [
	package.json,
	node_modules,
	Gruntfile.js,
	bower.json
]
keep_files: [
	# demos
	sideWidget.html,
	parallaxScrolling.html,
	javascripts/init.js,
	javascripts/parallaxScrolling.js,
	javascripts/sideWidget.js,
	# others
	images,
	javascripts/application.js,
	javascripts/jquery.min.js,
	javascripts/jquery.min.map,
	javascripts/vendor.js,
	stylesheets/application.css,
	stylesheets/application.css.map,
	stylesheets/bootstrap.css.map,
	stylesheets/vendor.css
]